# Generated by Django 5.2.8 on 2025-12-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_messages_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='icon',
            field=models.ImageField(blank='True', null='True', upload_to='threads/icons', verbose_name='Картинка'),
        ),
    ]
