# Generated by Django 5.2.8 on 2025-12-28 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_voting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='wrong1',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='wrong2',
            new_name='answer2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='wrong3',
            new_name='answer3',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='corect_answers',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='surveyresult',
            name='wrong_answers',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls_voting.question')),
                ('survey_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='polls_voting.surveyresult')),
            ],
        ),
    ]
