# Generated by Django 5.2.8 on 2025-12-03 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва події')),
                ('description', models.TextField(max_length=500, verbose_name='Опис')),
                ('date_start', models.DateField(verbose_name='Дата початку')),
                ('date_end', models.DateField(verbose_name='Дата завершення')),
                ('time_start', models.TimeField(verbose_name='Час початку')),
                ('time_end', models.TimeField(verbose_name='Час закінчення')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
                'ordering': ['-created_at'],
            },
        ),
    ]
